apiVersion: batch/v1
kind: CronJob
metadata:
  name: descargador-diario
spec:
  schedule: "15 08 27 * *"  # 3:00 AM todos los días
  startingDeadlineSeconds: 60
  concurrencyPolicy: Forbid # Evita que se corra uno nuevo si el anterior no ha terminado
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: descargador1
            image: descargador1:latest # Asegúrate de que la imagen esté en tu Docker local
            imagePullPolicy: Never      # Obliga a K8s a usar la imagen local de tu PC
            env:
            - name: ANIO1
              value: "2014"
            - name: ANIO2
              value: "2027"
            - name: PREFIJO
              value: "https://www.asfi.gob.bo/sites/default/files/estadisticaif/bancos_multiples"
            - name: SUFIJO
              value: "_BMU_EstadosFinancierosDesagregados.zip"
            - name: RUTA
              value: "dvcdatasets/desagregados7"
            volumeMounts:
            - name: espacio-trabajo
              mountPath: /data
          restartPolicy: OnFailure
          volumes:
          - name: espacio-trabajo
            persistentVolumeClaim:
              claimName: pvc-datos